### ISSUE TITLE
问题1 同步库表出现字段长度不够问题

### ISSUE THREAD

**Issue by zhmz1326** [jm-team/DevMasterWeb#3]
![qq 20170331154707](https://cloud.githubusercontent.com/assets/285687/24541391/c989467a-1629-11e7-84e9-79f1a3fbdfcf.png)

严重: Servlet.service() for servlet [springMvc] in context with path [/DevMasterWeb] threw exception [Request processing failed; nested exception is com.jumore.dove.common.BusinessException: 同步库表信息失败] with root cause
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1

	at com.jumore.dove.dao.CommonDaoImpl.batchSave(CommonDaoImpl.java:232)
	at com.jumore.dove.service.BaseServiceImpl.batchSave(BaseServiceImpl.java:100)
	at com.jumore.devmaster.controller.ProjectController.addTableAndColumnInfo(ProjectController.java:199)
	at com.jumore.devmaster.controller.ProjectController.syncDatabase(ProjectController.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by crazylong** [comment]
name 长度增加到50
